### ISSUE TITLE
why the duration is 29 second

### ISSUE THREAD

**Issue by drfilter** [keunwoochoi/transfer_learning_music#3]
I found the following code
`librosa.load(audio_path, sr=SR, duration=LEN_SRC)`
the LEN_SRC=29. second,  Is there any problem with this duration?

**Comment by keunwoochoi** [comment]
No scientific reason, it's just the longest choice over the preview files I have. Most of preview clips are 30-60second.

**Comment by drfilter** [comment]
I have a lot of music files that are 3 to 5 minutes and how should I choose the duration? For example, choose the longest music time?

**Comment by keunwoochoi** [comment]
Hm..

 * A dirty workaround is to find a 29-second segment from each full track. 
 * Otherwise you (or I) could modify the code by i) changing the final max-pooling to be 'global' max pooling and ii) changing the time-axis length to be `None` when creating the convnet, so that the convnet can deal with varying input lengths.

**Comment by keunwoochoi** [comment]
Update: Try keras2.0 model which can deal with different lengths other than 29s.
